Models/ErrorViewModel.cs
namespace WebASPnet.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Vegetable.cs
using WebASPnet.Controllers;

namespace WebASPnet.Models

{
    public class Vegetable
    {
        public string Name { get; set; }
        public double Price
        {
            get;
            set;
        }

    }


}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebASPnet.Models;

namespace WebASPnet.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/MyController.cs
using Microsoft.AspNetCore.Mvc;
using WebASPnet.Models;

namespace WebASPnet.Controllers
{
    public class MyController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }


        public IActionResult FirstViewMethod()
        {
            List<Vegetable> vegetables = GetVegetablesList();
            return View(vegetables);
        }
        public ActionResult SecondViewMethod()
        {
            var vegetables = GetVegetablesList().OrderBy(x => x.Name).ToList();
            return View(vegetables);
        }
        public ActionResult ThridViewMethod()
        {
            var vegetables = GetVegetablesList().OrderBy(x => x.Name).ToList();
            return View(vegetables);
        }


        public List<Vegetable> GetVegetablesList()
        {
            List<Vegetable> plants = new List<Vegetable>();
            StreamReader StreamIn = new StreamReader("Vegetable.txt"); 
            string Str;
            for (int i = 1; (Str = StreamIn.ReadLine()) != null; i++)
            {
                string[] Veget = Str.Split('|');
                plants.Add(new Vegetable {Name = Veget[0].Trim(), Price = double.Parse(Veget[1])});
            }
            StreamIn.Close(); 
            return plants;
        }


    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/My/FirstViewMethod.cshtml
@using WebASPnet.Models
@model List<Vegetable>
@{ 
    ViewBag.Title = "Овощи c ценой";
}
<h2>Список овощей с ценой</h2>
@foreach(var vegetable in Model)
{
 <div>
     @vegetable.Name 
     @vegetable.Price
     </div>
}

Views/My/Index.cshtml
@{
    ViewData["Title"] = "Мои овощи";
}

<div class="text-left">
    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
        <ul class="navbar-nav flex-grow-1">
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="My" asp-action="FirstViewMethod">Овощи списком</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="My" asp-action="SecondViewMethod">Овощи в таблице</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="My" asp-action="ThridViewMethod">Сгруппированные овощи</a>
            </li>
        </ul>
    </div>
    

Views/My/SecondViewMethod.cshtml
@using WebASPnet.Models
@model List<Vegetable> 
@{
    ViewBag.Title = "Овощи таблицей с ценой";
}

<table class="table" style="width:20%">
    <thead>
        <tr>
            <th class="text-center">Наименование</th>
        </tr>
    </thread>
    <tbody>
        @foreach (var vegetable in Model)
            {
                <tr class="text-left">
                    <td>
                        @vegetable.Name 
                        @vegetable.Price
                        </td>
                </tr>
            }
    </tbody>
</table>

Views/My/ThridViewMethod.cshtml
@using WebASPnet.Models
@model List<Vegetable>
@{
    ViewBag.Title = "Таблица овощей с ценой";
}
<h2>Группировка овощей и их цена</h2>
@{
    var currentModel = Model.GroupBy(x => x.Name.Substring(0, 1)).ToList();
    for (int letterIndex=0;letterIndex<currentModel.Count();letterIndex++)
            {
                <table class="table" style="width:20%; border:1px solid;">
                    <thread>
                        <tr>
                            <th class="text-center">@currentModel[letterIndex].Key</th>
                        </tr>
                    </thread>
                    @for (int objectIndex=0;objectIndex<currentModel[letterIndex].Count();objectIndex++)
                    {
                        <tr class="text-left">
                            <td>
                            @currentModel[letterIndex].ElementAt(objectIndex).Name   
                            @currentModel[letterIndex].ElementAt(objectIndex).Price
                            </td>
                        </tr>
                    }
                </table>
            }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebASPnet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebASPnet.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebASPnet</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="My" asp-action="Index">Vegetables</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebASPnet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>